<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../public/style/general.css">

    <script src="https://kit.fontawesome.com/a81368914c.js"></script>
    <title>Show User</title>

    <style>
        body{
            padding: 15rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1> Users </h1>
        <?php 
            foreach($Users as $User) {
                echo '<p> E-mail: '.$User['email'].'</p>';
                echo '<p> Senha: '.$User['senha'].'</p>';
            }
        ?>
    </div>

</body>
</html>